### ISSUE TITLE
subfolder path bug?

### ISSUE THREAD

**Issue by architrent** [OctopusDeploy/gulp-octo#10] opened 2017-04-20 23:07 UTC
I'm having an issue getting pack to work when gulp.src is a subfolder instead of the project root.

The relevant bits of my app structure look like this:

* /root
  * /package
      * /fonts
      * /js
      * index.html
  * /src
      * /app
         * /stuff1
         * /stuff2
      * /fonts
      * index.html
  * gulpfile.js

For development purposes, I work on the files in the src folder. My gulp file minifies, concats, cache-busts, etc., everything in src and puts it all into the package folder, with the above structure.  This is all pretty standard stuff, and the contents of the /package folder are what I want to pack and publish.

However, when this task runs (with root as the cwd):

> gulp.src('./package/**/*')
> .pipe(octo.pack())
> .pipe(octo.push(...));

I get: 

> ...
> Packed 'my-project.1.0.13.zip' with 49 files
> D:\git\root\node_modules\@octopusdeploy\octopackjs\lib\pack.js:26
>     throw err;
>     ^

> Error: ENOENT: no such file or directory, stat 'D:\git\root\fonts'

This is very true. There is no such file or directory.  But I haven't asked octo to do anything with such a directory.  I've tried several variations on the glob, all with no results.  It seems like pack has a path bug somewhere.

**Comment by alxwest** [comment] 2017-05-05 15:10
I've encountered this bug. The problem is the relative path is used in pack.js (in gulp-octo) on line 44. To fix this I'd suggest to replace "file.contents" with "file.contents || file.base" on the same line.

@PaulStovell do you you want a patch?

**Comment by zentron** [comment] 2017-05-06 07:57
Hi @alxwest. Since these JS libraries are OS we encourage users to issue PRs. Please feel free to do so and we will review and merge as soon as possible.

**Comment by zentron** [comment] 2017-05-06 11:58
@architrent Ive merged a change as suggested by @alxwest. (https://github.com/OctopusDeploy/gulp-octo/commit/dc352783ef42dcf6d2aca2100e5c7c52102acb96) Thanks for both of your input with this project.

**Closed by zentron** 2017-05-06 11:58 UTC
